### ISSUE TITLE
Containerize and write CWL for Waltz

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#18]
Tool: Waltz
Location: https://github.com/juberpatel/Waltz
Version: 2.0

- [x]  Waltz Container
- [x]  Waltz CWL
- [x]  Run Test

**Comment by shalabhsuman** [comment]
I can take the Assignment for the issue.

**Comment by shalabhsuman** [comment]
As per discussion with the group, the current Docker image will be built based off the `Waltz v2.0 jar`. However once @juberpatel confirms the code clean up and version-control for Waltz, I will re-build the image, if needed.

**Comment by shalabhsuman** [comment]
While performing the test for this CMDLine tool, there is an error `Error: Could not find or load main class org.mskcc.juber.waltz.countreads.CountReads`. The base image for the image is `Java:8`. and the specific version while running the image is `openjdk version "1.8.0_111"`. I am assuming the error may be caused by incompatibility between this Java version and [`Waltz-2.0.jar`](https://github.com/juberpatel/Waltz/blob/master/Waltz-2.0.jar).
Also, was able to replicate the same error with `java version "1.7.0_75"` .

@juberpatel - any idea if we need a specific `version of Java` to run `Waltz`?
